# MySQL.  Versions 4.1 and 5.0 are recommended.
common: &common
  adapter: mysql
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: wine_dev

staging:
  <<: *common
  database: wine_staging

test: &test
  <<: *common
  database: wine_test

release_candidate: &release_candidate
  <<: *common
  database: wine_rc

cucumber:
  <<: *release_candidate

sauce:
  <<: *test